version: '3.8'

services:
  # 1. 젠킨스 컨테이너
  jenkins:
    image: jenkins/jenkins:lts-jdk17  # 자바 17 지원 LTS 버전
    container_name: jenkins_server
    user: root                        # 도커 명령어를 쓰기 위해 권한 필요
    ports:
      - "9090:8080"                   # 웹 접속 포트
      - "50000:50000"                 # 에이전트 연결 포트
    volumes:
      - ./jenkins_home:/var/jenkins_home  # 젠킨스 데이터 영구 저장 (호스트 경로 매핑)
      - /var/run/docker.sock:/var/run/docker.sock # 젠킨스 내부에서 도커 사용 (DinD)
    environment:
      - TZ=Asia/Seoul                 # 시간대 설정
    networks:
      - my-network                    # db와 같은 네트워크 사용
    restart: always

  # 2. MySQL 데이터베이스
  db:
    image: mysql:8.0
    container_name: mysql_server
    environment:
      MYSQL_ROOT_PASSWORD: root       # 루트 비밀번호 (변경 가능)
      MYSQL_DATABASE: board_db        # 초기 생성할 DB 이름
      TZ: Asia/Seoul
    command: # 한글 깨짐 방지 설정 (utf8mb4)
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    ports:
      - "3307:3306"                   # 호스트에서 DB 접속 허용 (DBeaver 등)
    volumes:
      - ./db_data:/var/lib/mysql      # DB 데이터 영구 저장
    networks:
      - my-network
    restart: always

# 3. 네트워크 정의
networks:
  my-network:
    driver: bridge